CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Models/Student.cs
namespace BiblioDatCore.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Class to represent Student model objects.
    /// </summary>
    public class Student
    {
        /// <summary>
        /// Gets or sets Id of student.
        /// </summary>
        [Display(Name = "Student Id")]
        [Required]
        [Range(1, 99999)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets first name of student.
        /// </summary>
        [Display(Name = "Student First Name")]
        [Required]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets last name of student.
        /// </summary>
        [Display(Name = "Student Last Name")]
        [Required]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets gender of student.
        /// </summary>
        [Display(Name = "Student Gender")]
        [Required]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or sets class year of student.
        /// </summary>
        [Range(1, 14)]
        [Display(Name = "Student Class Year")]
        [Required]
        public int ClassYear { get; set; }

        /// <summary>
        /// Gets or sets date of birth of student.
        /// </summary>
        [Display(Name = "Student Date of Birth")]
        [Range(typeof(DateTime), "1900-01-01", "2020-01-01", ErrorMessage = "Value for {0} must be between {1} and {2}")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime DateOfBirth { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Controllers/StudentsController.cs
namespace BiblioDatCore.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using BiblioDatCore.Logic;
    using BiblioDatCore.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Class for Students Controller.
    /// </summary>
    public class StudentsController : Controller
    {
        private ILogic logic;
        private IMapper mapper;
        private StudentListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentsController"/> class.
        /// </summary>
        /// <param name="logic">Logic object for database operations.</param>
        /// <param name="mapper">Mapper object for entity/model class conversions.</param>
        public StudentsController(ILogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new StudentListViewModel();
            this.vm.EditedStudent = new Models.Student();

            IList<Data.Models.Student> students = logic.ListAllStudent();
            this.vm.ListOfStudents = mapper.Map<IList<Data.Models.Student>, List<Models.Student>>(students);
        }

        /// <summary>
        /// Method to get Index page.
        /// </summary>
        /// <returns>StudentsIndex view.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("StudentsIndex", this.vm);
        }

        /// <summary>
        /// Method to get Details page.
        /// </summary>
        /// <param name="id">Id of student to print.</param>
        /// <returns>StudentsDetail view.</returns>
        public IActionResult Details(int id)
        {
            return this.View("StudentsDetails", this.GetStudentModel(id));
        }

        /// <summary>
        /// Method to process remove actions.
        /// </summary>
        /// <param name="id">Id of student to remove.</param>
        /// <returns>Redirect action to Index.</returns>
        public IActionResult Remove(int id)
        {
            try
            {
                this.logic.RemoveStudent(id);
                this.TempData["editResult"] = "Delete successful";
            }
            catch (Exception e)
            {
                this.TempData["editResult"] = "Delete failed: " + e.Message;
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Method for processing edit get request.
        /// </summary>
        /// <param name="id">Id of student to be edited.</param>
        /// <returns>Index page with editor.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedStudent = this.GetStudentModel(id);
            return this.View("StudentsIndex", this.vm);
        }

        /// <summary>
        /// Method for processing Edit post request.
        /// </summary>
        /// <param name="student">Student edited.</param>
        /// <param name="editAction">Type of edit (add new or edit existing).</param>
        /// <returns>Redirect to index page.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Student student, string editAction)
        {
            if (this.ModelState.IsValid && student != null)
            {
                this.TempData["editResult"] = "Edit successful.";
                try
                {
                    if (editAction == "AddNew")
                    {
                        this.logic.InsertStudent(this.ConvertStudentToEntity(student));
                    }
                    else
                    {
                        this.logic.ChangeStudent(student.Id, this.ConvertStudentToEntity(student));
                    }
                }
                catch (Exception e)
                {
                    this.TempData["editResult"] = "Edit failed: " + e.Message;
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedStudent = student;
                return this.View("StudentsIndex", this.vm);
            }
        }

        private Models.Student GetStudentModel(int id)
        {
            Data.Models.Student oneStudent = this.logic.GetOneStudent(id);
            return this.mapper.Map<Data.Models.Student, Models.Student>(oneStudent);
        }

        private Data.Models.Student ConvertStudentToEntity(Models.Student student)
        {
            return this.mapper.Map<Models.Student, Data.Models.Student>(student);
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Views/Students/StudentsDetails.cshtml
@model BiblioDatCore.Web.Models.Student

@{
    ViewData["Title"] = "StudentsDetails";
}

<h2>Datasheet of one student</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FirstName)</td>
        <td>@Html.DisplayFor(m => m.FirstName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LastName)</td>
        <td>@Html.DisplayFor(m => m.LastName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Gender)</td>
        <td>@Html.DisplayFor(m => m.Gender)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ClassYear)</td>
        <td>@Html.DisplayFor(m => m.ClassYear)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.DateOfBirth)</td>
        <td>@Html.DisplayFor(m => m.DateOfBirth)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Views/Students/StudentsEdit.cshtml
@model BiblioDatCore.Web.Models.Student

<h2>StudentsEdit</h2>

@using (Html.BeginForm("Edit", "Students"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @*Html.HiddenFor(m => m.Id)*@
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Id)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Id)</div>

    <div class="editor-label">@Html.LabelFor(m => m.FirstName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FirstName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.LastName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LastName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Gender)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Gender)</div>

    <div class="editor-label">@Html.LabelFor(m => m.ClassYear)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ClassYear)</div>

    <div class="editor-label">@Html.LabelFor(m => m.DateOfBirth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.DateOfBirth)</div>

    <input type="submit" value="SUBMIT" />
}

CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Views/Students/StudentsIndex.cshtml
@model BiblioDatCore.Web.Models.StudentListViewModel

@{
    ViewData["Title"] = "StudentsIndex";
}

<h2>Students Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("StudentsEdit", Model.EditedStudent)

@await Html.PartialAsync("StudentsList", Model.ListOfStudents)

CSHARP/OENIK_PROG3_2019_2_CHN1RD/BiblioDatCore.Web/Views/Students/StudentsList.cshtml
@model IEnumerable<BiblioDatCore.Web.Models.Student>

<h2>StudentsList</h2>

@if (Model.Count() == 0)
{
    <p>No data found in database.</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().FirstName)</th>
            <th>@Html.DisplayNameFor(m => m.First().LastName)</th>
            <th>@Html.DisplayNameFor(m => m.First().ClassYear)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var student in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => student.FirstName)</td>
                <td>@Html.DisplayFor(m => student.LastName)</td>
                <td>@Html.DisplayFor(m => student.ClassYear)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = student.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = student.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = student.Id })</td>
            </tr>
        }
    </table>
}